// Legacy pages-sitemap — disabled. Sitemap is now generated by next-sitemap at build time.
export async function GET(): Promise<Response> {
  return new Response('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>', {
    headers: { 'Content-Type': 'application/xml' },
  })
}
