/**
 * Shared Lucide icon select options used across all collections and globals.
 * Add new icons here and they become available everywhere.
 */
export const lucideIconOptions = [
  { label: 'Activity', value: 'Activity' },
  { label: 'AlertTriangle', value: 'AlertTriangle' },
  { label: 'ArrowRight', value: 'ArrowRight' },
  { label: 'AtSign', value: 'AtSign' },
  { label: 'BarChart3', value: 'BarChart3' },
  { label: 'Bell', value: 'Bell' },
  { label: 'BookOpen', value: 'BookOpen' },
  { label: 'Brain', value: 'Brain' },
  { label: 'Briefcase', value: 'Briefcase' },
  { label: 'Building2', value: 'Building2' },
  { label: 'Calendar', value: 'Calendar' },
  { label: 'CheckSquare', value: 'CheckSquare' },
  { label: 'Clock', value: 'Clock' },
  { label: 'Code', value: 'Code' },
  { label: 'CreditCard', value: 'CreditCard' },
  { label: 'Database', value: 'Database' },
  { label: 'DollarSign', value: 'DollarSign' },
  { label: 'EyeOff', value: 'EyeOff' },
  { label: 'FileText', value: 'FileText' },
  { label: 'Filter', value: 'Filter' },
  { label: 'GitBranch', value: 'GitBranch' },
  { label: 'Globe', value: 'Globe' },
  { label: 'Hash', value: 'Hash' },
  { label: 'Heart', value: 'Heart' },
  { label: 'HelpCircle', value: 'HelpCircle' },
  { label: 'Layers', value: 'Layers' },
  { label: 'LayoutDashboard', value: 'LayoutDashboard' },
  { label: 'Lightbulb', value: 'Lightbulb' },
  { label: 'Link', value: 'Link' },
  { label: 'ListX', value: 'ListX' },
  { label: 'Mail', value: 'Mail' },
  { label: 'MapPin', value: 'MapPin' },
  { label: 'MessageCircle', value: 'MessageCircle' },
  { label: 'Phone', value: 'Phone' },
  { label: 'Plug', value: 'Plug' },
  { label: 'RefreshCw', value: 'RefreshCw' },
  { label: 'Rocket', value: 'Rocket' },
  { label: 'Search', value: 'Search' },
  { label: 'Send', value: 'Send' },
  { label: 'Shield', value: 'Shield' },
  { label: 'Sparkles', value: 'Sparkles' },
  { label: 'SplitSquareHorizontal', value: 'SplitSquareHorizontal' },
  { label: 'Target', value: 'Target' },
  { label: 'TrendingDown', value: 'TrendingDown' },
  { label: 'TrendingUp', value: 'TrendingUp' },
  { label: 'Unlink', value: 'Unlink' },
  { label: 'Upload', value: 'Upload' },
  { label: 'Users', value: 'Users' },
  { label: 'Zap', value: 'Zap' },
]
